services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $client: '@http_client'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Service\Calculator\CommissionCalculator:
        arguments:
            $rules:
                - '@App\Service\Rule\DepositRule'
                - '@App\Service\Rule\BusinessWithdrawRule'
                - '@App\Service\Rule\PrivateWithdrawRule'

    App\Service\Currency\ExchangeRateService:
        arguments:
            $apiKey: '%env(EXCHANGE_API_KEY)%'
